services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    ports: ["8000:8000"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
